CREATE TABLE AUDITORIA (
    ID_AUDITORIA        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TABLA               VARCHAR2(200),
    ID_REGISTRO         NUMBER,
    OPERACION           VARCHAR2(10),              
    USUARIO_BD          VARCHAR2(50),              
    FECHA_EVENTO        TIMESTAMP DEFAULT SYSTIMESTAMP,
    CAMPO_MODIFICADO    VARCHAR2(1000),            
    VALOR_ANTERIOR      VARCHAR2(4000),
    VALOR_NUEVO         VARCHAR2(4000)
);

CREATE OR REPLACE TRIGGER TRG_AUD_TRANSACCIONES
AFTER INSERT OR UPDATE OR DELETE ON TRANSACCIONES
FOR EACH ROW
DECLARE
    v_operacion VARCHAR2(10);
BEGIN
    IF INSERTING THEN
        v_operacion := 'INSERT';
        INSERT INTO AUDITORIA (TABLA, ID_REGISTRO, OPERACION, USUARIO_BD, FECHA_EVENTO, VALOR_NUEVO)
        VALUES ('TRANSACCIONES', :NEW.ID, v_operacion, SYS_CONTEXT('USERENV', 'SESSION_USER'), SYSTIMESTAMP,
                'Registro insertado');

    ELSIF UPDATING THEN
        v_operacion := 'UPDATE';
        INSERT INTO AUDITORIA (TABLA, ID_REGISTRO, OPERACION, USUARIO_BD, FECHA_EVENTO, VALOR_ANTERIOR, VALOR_NUEVO)
        VALUES ('TRANSACCIONES', :OLD.ID, v_operacion, SYS_CONTEXT('USERENV', 'SESSION_USER'), SYSTIMESTAMP,
                'Datos antiguos', 'Datos actualizados');

    ELSIF DELETING THEN
        v_operacion := 'DELETE';
        INSERT INTO AUDITORIA (TABLA, ID_REGISTRO, OPERACION, USUARIO_BD, FECHA_EVENTO, VALOR_ANTERIOR)
        VALUES ('TRANSACCIONES', :OLD.ID, v_operacion, SYS_CONTEXT('USERENV', 'SESSION_USER'), SYSTIMESTAMP,
                'Registro eliminado');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_AUD_TARJETAS
AFTER INSERT OR UPDATE OR DELETE ON TARJETAS
FOR EACH ROW
DECLARE
    v_operacion VARCHAR2(10);
BEGIN
    IF INSERTING THEN
        v_operacion := 'INSERT';
        INSERT INTO AUDITORIA (TABLA, ID_REGISTRO, OPERACION, USUARIO_BD, FECHA_EVENTO, VALOR_NUEVO)
        VALUES ('TARJETAS', :NEW.ID, v_operacion, SYS_CONTEXT('USERENV', 'SESSION_USER'), SYSTIMESTAMP,
                'Registro insertado');

    ELSIF UPDATING THEN
        v_operacion := 'UPDATE';
        INSERT INTO AUDITORIA (TABLA, ID_REGISTRO, OPERACION, USUARIO_BD, FECHA_EVENTO, VALOR_ANTERIOR, VALOR_NUEVO)
        VALUES ('TARJETAS', :OLD.ID, v_operacion, SYS_CONTEXT('USERENV', 'SESSION_USER'), SYSTIMESTAMP,
                'Datos antiguos', 'Datos actualizados');

    ELSIF DELETING THEN
        v_operacion := 'DELETE';
        INSERT INTO AUDITORIA (TABLA, ID_REGISTRO, OPERACION, USUARIO_BD, FECHA_EVENTO, VALOR_ANTERIOR)
        VALUES ('TARJETAS', :OLD.ID, v_operacion, SYS_CONTEXT('USERENV', 'SESSION_USER'), SYSTIMESTAMP,
                'Registro eliminado');
    END IF;
END;
/

/

